### PR TITLE
Implement #4

### PR DESCRIPTION
**Pull request by tokejepsen**
This is a work-in-progress PR for #4, while I figure out Travis and Appveyor.

### CODE REVIEW

**Comment by tokejepsen** [comment]
Woot woot! Passing the first test on Appveyor and Travis :)

Had to drop support for Python 3.2 and 3.3 on Travis as it did not install with pip. Python 3.2 is not supported by pytest, but Python 3.3 should but just not on Travis.

I'm guessing we can assume it to work on OSX when it passes on Travis?

**Comment by mottosso** [comment]
Travis supports OSX too. :) Up to you whether you'd like to the library to support it.

Re Python 3.2, I think it's safe to assume people are using 3.5 and above, anything below that is pretty bare.

**Comment by tokejepsen** [comment]
> Up to you whether you'd like to the library to support it.

Maybe selfish reasons, but I'm going to leave OSX unsupported until its requested by someone else.

**Comment by mottosso** [comment]
Odds are it's already supported.

https://stackoverflow.com/questions/10327804/how-to-create-a-hard-link-from-within-a-python-script-on-a-mac

I think adding OSX to Travis should be a single flag.

**Comment by tokejepsen** [comment]
Have you done testing on OSX before on Travis?

**Comment by mottosso** [comment]
Yeah, why?

**Comment by tokejepsen** [comment]
I'm getting an odd error on all OSX builds on Travis

```The command "sudo tar xjf python-2.6.tar.bz2 --directory /" failed and exited with 1 during .```

**Comment by mottosso** [comment]
I can't remember how I handled that, but some quick Googling revealed that it looks like Python isn't available via Travis on OSX per default.

- https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-289140791

`brew` might be a better option. But I'd understand if it'd be a little too much, unrewarding work to dive into that.

**Comment by tokejepsen** [comment]
Do you remember where you are using OSX on Travis?

What I don't get from that comment is that it only seems to install a specific python version for all the builds.

I'm kinda thinking of leaving OSX support until Travis can support it natively.

**Comment by mottosso** [comment]
> I'm kinda thinking of leaving OSX support until Travis can support it natively.

Yeah, screw it. Let's tackle it once we or someone else use OSX.

**Comment by tokejepsen** [comment]
Ok, this is ready to be merged. What do you think?

**Pull request merged**
