### PR TITLE
Default to hardlink

### PR DESCRIPTION
**Pull request by mottosso**
Implements #2 and makes a few cosmetics changes.

Have been using this to symlink files both locally (Windows) and on a network (Windows to Linux) and it works well!

### CODE REVIEW

**Comment by tokejepsen** [comment]
Do you think the test needs to reflect the assumption of having HARDLINK as default?

**Comment by mottosso** [comment]
No I think it's better to have the test refer to the argument explicitly, that way it'll warn if we accidentally change it.

**Comment by tokejepsen** [comment]
How about a test for the assumption?

Don't know how verbose/rigid these tests needs to be.

**Comment by mottosso** [comment]
> Don't know how verbose/rigid these tests needs to be.

For that I can think of only one way to learn, experience. :) The goal is for your tests to tell you when things unintentionally breaks. Much like with publishing. I would either implement more than you think is necessary, or less and see the pros/cons for yourself. I don't think there is any right answer, but rather something personal and this time you're the maintainer.

**Comment by tokejepsen** [comment]
Thank you @mottosso for the PR :)

**Pull request merged**
